### ISSUE TITLE
Bewertungsfunktion

### ISSUE THREAD

**Issue by patrickdaumann** [patrickdaumann/BierCheck24#3]
- Welche Kriterien sollen bewertet werden können ? -> Kommentar

**Comment by adrirula** [comment]
Etwas ausführlicher:
Aroma: Das Aroma des Bieres kann je nach Biersorte variieren und kann von fruchtig und blumig bis hin zu malzig und hopfig reichen.
Aussehen: Die Farbe, Trübung und Schaumkrone können alle dazu beitragen, das Aussehen eines Bieres zu bewerten.
Geschmack: Der Geschmack des Bieres kann von bitter und würzig bis hin zu süß und fruchtig reichen.
Körper: Der Körper des Bieres bezieht sich auf seine Textur und Dichte, die durch die Menge an Malz und Hopfen im Bier beeinflusst werden können.
Abgang: Der Abgang des Bieres bezieht sich auf den Geschmack und das Gefühl, das im Mund bleibt, nachdem das Bier getrunken wurde.
Kohlensäuregehalt: Der Kohlensäuregehalt des Bieres kann einen Einfluss auf das Mundgefühl und die Textur des Bieres haben.
Alkoholgehalt: Der Alkoholgehalt kann variieren und kann die Intensität des Geschmacks beeinflussen.
Balance: Die Balance des Bieres bezieht sich auf das Gleichgewicht zwischen den verschiedenen Geschmacks- und Aromakomponenten.
Diese Eigenschaften können einzeln oder in Kombination bewertet werden, um das Bier zu beurteilen.

**Comment by KesperM** [comment]
Äußerst präzise, ich persönlich finde Kategorien wir Aroma oder Abgang schwierig hinsichtlich der Darstellung, analog zu Umfragen hat man hier dann das Problem des Freitextfeldes und müsste für eine ordentliche Bewertung eigentlich Auswahlpunkte vorgeben (bspw. beim Aroma: Fruchtig ; Blumig ; Malzig ; Hopfig)
Darüber hinaus könnte man analog einer Umfrage dem User bei einem bereits existierenden Bier Fragen entsprechend der Kategorien/Kriterien stellen, existiert das Bier noch nicht, muss der User das Bier erst anlegen und anschließend bewerten
